USE ecommerce;

SET @empty_embedding = VEC_FromText(CONCAT('[', REPEAT('0,', 3071), '0]'));

INSERT INTO reviews (product_id, title, review_text, review_date, rating, embedding) VALUES
-- Nature Made Multi for Him (product 1) - 20 reviews, ~70% positive
(1, 'Morning energy stays high', 'Taking this with breakfast keeps me alert through long shifts and I rarely crash.', '2026-01-05', 5, @empty_embedding),
(1, 'Easy on my stomach', 'Unlike other multis this one never upsets my stomach, even before workouts.', '2026-01-15', 4, @empty_embedding),
(1, 'Travel ready support', 'Packed a week of tablets for a conference and felt energized despite late nights.', '2026-01-25', 4, @empty_embedding),
(1, 'Supports my workouts', 'Recovery between lifting sessions feels faster since adding this vitamin.', '2026-02-02', 5, @empty_embedding),
(1, 'Keeps lab numbers steady', 'Recent bloodwork looked great and my doctor told me to keep using it.', '2026-02-12', 4, @empty_embedding),
(1, 'Helps hair and nails', 'Noticed stronger nails and less shedding after two months.', '2026-02-22', 4, @empty_embedding),
(1, 'Boosted focus at work', 'Afternoon meetings are easier because I stay mentally sharp.', '2026-03-03', 5, @empty_embedding),
(1, 'Convenient once-a-day routine', 'One tablet with coffee and I am done for the day.', '2026-03-12', 4, @empty_embedding),
(1, 'Trusted brand quality', 'USP mark gives me confidence and the results back it up.', '2026-03-21', 5, @empty_embedding),
(1, 'Affordable compared to others', 'Great value for the ingredient mix and 90-count bottle lasts long.', '2026-04-01', 4, @empty_embedding),
(1, 'Improved overall mood', 'Felt less irritable once my vitamin D levels climbed.', '2026-04-10', 5, @empty_embedding),
(1, 'No more afternoon slump', 'Energy stays steadier so I skip the sugary snacks.', '2026-04-20', 4, @empty_embedding),
(1, 'Smoothie friendly', 'Crushes easily so I can blend it when I do not want to swallow pills.', '2026-05-01', 4, @empty_embedding),
(1, 'Less soreness after runs', 'B complex seems to help recovery from weekend long runs.', '2026-05-10', 5, @empty_embedding),
(1, 'Tablets are too big', 'Wish they were smaller because swallowing them is a chore.', '2026-05-18', 2, @empty_embedding),
(1, 'Caused mild acne', 'Skin flared up after a week of use which went away once I stopped.', '2026-05-26', 2, @empty_embedding),
(1, 'Upset my stomach', 'Even with food I felt queasy for hours, so I switched brands.', '2026-06-04', 2, @empty_embedding),
(1, 'Made me jittery', 'Felt wired and could not sit still, so this is not for me.', '2026-06-12', 2, @empty_embedding),
(1, 'No noticeable change', 'Finished a bottle and felt exactly the same.', '2026-06-20', 3, @empty_embedding),
(1, 'Chalky taste', 'Coating dissolves fast and leaves a chalky taste in my mouth.', '2026-06-28', 2, @empty_embedding),

-- Gold Standard 100% Whey Protein (product 2) - 20 reviews, 50/50 polarity
(2, 'Mixes instantly in water', 'Shaker bottle plus cold water and it is perfectly smooth.', '2026-01-03', 5, @empty_embedding),
(2, 'Clean ingredient list', 'Appreciate the transparent label and minimal fillers.', '2026-01-11', 4, @empty_embedding),
(2, 'Great recovery drink', 'Muscles feel less sore the day after heavy deadlifts.', '2026-01-19', 5, @empty_embedding),
(2, 'Versatile in recipes', 'Use it in overnight oats and it tastes like dessert.', '2026-01-27', 4, @empty_embedding),
(2, 'Keeps my macros on track', 'Easy way to add 24g protein without extra carbs.', '2026-02-04', 4, @empty_embedding),
(2, 'Chocolate flavor is fantastic', 'Tastes like cocoa milk when blended with almond milk.', '2026-02-12', 5, @empty_embedding),
(2, 'Supports lean gains', 'Added a scoop post workout and finally broke a plateau.', '2026-02-20', 4, @empty_embedding),
(2, 'Value tub lasts a month', 'Training five days a week and the big tub goes far.', '2026-02-28', 4, @empty_embedding),
(2, 'Low sugar treat', 'Satisfies sweet cravings without derailing my cut.', '2026-03-07', 5, @empty_embedding),
(2, 'Stacks well with creatine', 'Digestive comfort is great even when stacking supplements.', '2026-03-15', 4, @empty_embedding),
(2, 'Too sweet and artificial', 'Flavoring tastes like pure syrup and lingers.', '2026-03-23', 2, @empty_embedding),
(2, 'Bloating every time', 'My stomach hurts after each shake even with lactase pills.', '2026-03-31', 2, @empty_embedding),
(2, 'Recent batch is sandy', 'Texture changed and now leaves grit at the bottom.', '2026-04-08', 2, @empty_embedding),
(2, 'Price jumped overnight', 'Love the product but the new price feels excessive.', '2026-04-16', 3, @empty_embedding),
(2, 'Vanilla tastes chemical', 'Reminds me of plastic and I could not finish the serving.', '2026-04-24', 2, @empty_embedding),
(2, 'Clogs my shaker ball', 'No matter how long I shake, there are stubborn clumps.', '2026-05-02', 2, @empty_embedding),
(2, 'Caused breakouts', 'Noticed acne along my jawline whenever I used it.', '2026-05-10', 2, @empty_embedding),
(2, 'Hard on lactose-sensitive folks', 'Even half scoops gave me cramps.', '2026-05-18', 2, @empty_embedding),
(2, 'Lid cracked after a week', 'Container quality feels cheaper than before.', '2026-05-26', 2, @empty_embedding),
(2, 'Customer service slow to respond', 'Took three weeks to answer a simple question.', '2026-06-03', 2, @empty_embedding),

-- Nature Made Fish Oil 1200mg (product 3) - 20 reviews, ~30% positive
(3, 'Truly no fish burps', 'Even when I take them at lunch there is zero aftertaste.', '2026-01-06', 5, @empty_embedding),
(3, 'Lab numbers improved', 'Triglycerides dropped 20 points after two months.', '2026-01-14', 4, @empty_embedding),
(3, 'Easy to swallow capsules', 'Softgels are slick and go down without water.', '2026-01-22', 4, @empty_embedding),
(3, 'Great value twin pack', 'Stocked up during a sale and saved a bundle.', '2026-01-30', 4, @empty_embedding),
(3, 'Helped loosen stiff knees', 'Morning walks are more comfortable now.', '2026-02-07', 4, @empty_embedding),
(3, 'Doctor approved', 'Primary care physician encouraged me to stay on this brand.', '2026-02-15', 5, @empty_embedding),
(3, 'Capsules fused together', 'Hot weather melted them into a sticky block.', '2026-02-23', 2, @empty_embedding),
(3, 'Persistent fishy taste', 'Even freezing them did not stop the fish burps.', '2026-03-04', 2, @empty_embedding),
(3, 'Made me nauseous', 'Felt sick within minutes of taking each dose.', '2026-03-12', 2, @empty_embedding),
(3, 'Softgels leaked', 'Oil coated the inside of the bottle and smelled terrible.', '2026-03-20', 2, @empty_embedding),
(3, 'No change in blood tests', 'Cholesterol barely moved after three months.', '2026-03-28', 2, @empty_embedding),
(3, 'Difficult to swallow', 'Size is too large and gets stuck in my throat.', '2026-04-05', 2, @empty_embedding),
(3, 'Upset stomach daily', 'Caused cramps every night so I tossed the bottle.', '2026-04-13', 2, @empty_embedding),
(3, 'Smells rancid', 'Opened a new bottle to a strong fish smell and had to return it.', '2026-04-21', 1, @empty_embedding),
(3, 'Short dated batch', 'Expiration is only two months out which feels risky.', '2026-04-29', 2, @empty_embedding),
(3, 'Made my skin oily', 'Breakouts along my hairline started right after taking these.', '2026-05-07', 2, @empty_embedding),
(3, 'Coating sticks to tongue', 'Leaves a gelatin film and weird texture.', '2026-05-15', 2, @empty_embedding),
(3, 'Difficult to travel with', 'Heat made the capsules deform during a trip.', '2026-05-23', 2, @empty_embedding),
(3, 'Bottle leaks', 'Found oil pooling under the bottle after a week.', '2026-05-31', 1, @empty_embedding),
(3, 'Made me dizzy', 'Felt lightheaded every time I used it.', '2026-06-08', 1, @empty_embedding),
(3, 'Terrible gelatin taste', 'Capsule shell tastes like rubber and sticks to my teeth.', '2026-06-16', 2, @empty_embedding),

-- Sports Research Vitamin D3 K2 (product 4) - 20 reviews, roughly 50/50 but skewed by request
(4, 'Fast boost to vitamin D', 'Blood test confirmed my levels are finally optimal.', '2026-01-04', 5, @empty_embedding),
(4, 'Small capsules are convenient', 'Tiny gelcaps make daily dosing effortless.', '2026-01-12', 4, @empty_embedding),
(4, 'Pairs great with calcium', 'Taking this alongside calcium improved my bone scan.', '2026-01-20', 4, @empty_embedding),
(4, 'Feels like sunshine in a bottle', 'Noticeable mood lift during gloomy weeks.', '2026-01-28', 5, @empty_embedding),
(4, 'Trust the coconut oil base', 'Absorption seems better than dry tablets I tried.', '2026-02-05', 4, @empty_embedding),
(4, 'Easy to travel with', 'Kept me healthy on a long trip with little sun exposure.', '2026-02-13', 4, @empty_embedding),
(4, 'No aftertaste', 'Capsules go down smooth and leave no flavor behind.', '2026-02-21', 4, @empty_embedding),
(4, 'Improved focus', 'Felt mentally sharper within weeks of starting.', '2026-03-01', 4, @empty_embedding),
(4, 'Joint comfort returned', 'K2 seems to help my knees feel less crunchy.', '2026-03-09', 4, @empty_embedding),
(4, 'Winter mood lifter', 'Seasonal blues were much less intense this year.', '2026-03-17', 4, @empty_embedding),
(4, 'Capsules melted together', 'Received a bottle of soft clumps during shipping.', '2026-03-25', 2, @empty_embedding),
(4, 'Dosage felt too strong', 'Developed restlessness and insomnia until I stopped.', '2026-04-02', 2, @empty_embedding),
(4, 'Caused heartburn', 'Burning sensation every time, even with meals.', '2026-04-10', 2, @empty_embedding),
(4, 'Gel caps stick', 'Have to pry them apart which ruins several servings.', '2026-04-18', 1, @empty_embedding),
(4, 'Greasy aftertaste', 'Coconut oil flavor hangs around for hours.', '2026-04-26', 2, @empty_embedding),
(4, 'Made me jittery', 'Felt wired and anxious until the evening.', '2026-05-04', 1, @empty_embedding),
(4, 'Oil leaked in luggage', 'Cap does not seal well and ruined my toiletry bag.', '2026-05-12', 2, @empty_embedding),
(4, 'Raised calcium too high', 'Doctor told me to stop because my labs spiked.', '2026-05-20', 1, @empty_embedding),
(4, 'Developed hives', 'Experienced itchy patches after each dose.', '2026-05-28', 1, @empty_embedding),
(4, 'Customer support unhelpful', 'Never heard back about a defective bottle.', '2026-06-05', 2, @empty_embedding),
(4, 'Capsules smell rancid', 'Fresh bottle smelled off and I could not trust it.', '2026-06-13', 1, @empty_embedding),

-- Culturelle Daily Probiotic (product 5) - 20 reviews, mixed polarity
(5, 'Helped calm my skin', 'Cleared stubborn blemishes once my digestion improved.', '2026-01-07', 5, @empty_embedding),
(5, 'Great during travel', 'Kept my stomach happy through two weeks abroad.', '2026-01-16', 4, @empty_embedding),
(5, 'Bloating eased by week three', 'Patience paid off and I feel lighter now.', '2026-01-25', 4, @empty_embedding),
(5, 'Kids tolerate it too', 'Split capsules into yogurt for my teens and it helped them.', '2026-02-03', 5, @empty_embedding),
(5, 'Shelf stable convenience', 'Love that it does not require refrigeration.', '2026-02-11', 4, @empty_embedding),
(5, 'Immune support bump', 'Fewer colds this winter which I credit to this probiotic.', '2026-02-19', 5, @empty_embedding),
(5, 'Less sugar cravings', 'Balanced gut seems to make sweets less tempting.', '2026-02-27', 4, @empty_embedding),
(5, 'Worked after antibiotics', 'Rebuilt my gut after a strong antibiotic course.', '2026-03-06', 5, @empty_embedding),
(5, 'Pricey but worth it', 'Subscription discounts help and my digestion is steady.', '2026-03-14', 4, @empty_embedding),
(5, 'Morning routine lifesaver', 'One capsule with water keeps me regular.', '2026-03-22', 5, @empty_embedding),
(5, 'Too many capsules per day', 'Taking three is hard to remember and results fade when I miss doses.', '2026-03-30', 3, @empty_embedding),
(5, 'Initial gas and cramping', 'Took a full month before my stomach settled down.', '2026-04-07', 3, @empty_embedding),
(5, 'No change for me', 'Finished a box and digestion stayed the same.', '2026-04-15', 2, @empty_embedding),
(5, 'Caused more bloating', 'Felt puffier after each capsule so I stopped.', '2026-04-23', 2, @empty_embedding),
(5, 'Hard to swallow capsules', 'They are surprisingly large and get stuck.', '2026-05-01', 2, @empty_embedding),
(5, 'Made me drowsy', 'Odd side effect but I felt sleepy after taking it.', '2026-05-09', 2, @empty_embedding),
(5, 'Too expensive to maintain', 'Great results but monthly cost is steep.', '2026-05-17', 3, @empty_embedding),
(5, 'Packaging flimsy', 'Foil blister tears and exposes capsules to air.', '2026-05-25', 2, @empty_embedding),
(5, 'Strange taste when opened', 'Powder smells sour if the capsule cracks.', '2026-06-02', 2, @empty_embedding),
(5, 'Did not reduce IBS flares', 'Symptoms stayed the same after two bottles.', '2026-06-10', 2, @empty_embedding),

-- Natrol Melatonin 5mg (product 6) - 20 reviews, improvised balance
(6, 'Perfect gentle nudge to sleep', 'Half a tablet helps me doze off without heavy grogginess.', '2026-01-09', 4, @empty_embedding),
(6, 'Time release really works', 'I stay asleep all night instead of waking at 2 a.m.', '2026-01-18', 5, @empty_embedding),
(6, 'Jet lag reset tool', 'Used it flying to Europe and adjusted quickly.', '2026-01-27', 4, @empty_embedding),
(6, 'Great for shift work', 'Helps me flip from nights to days without prescription meds.', '2026-02-05', 4, @empty_embedding),
(6, 'No hangover feeling', 'Wake up clearheaded which is rare for sleep aids.', '2026-02-13', 5, @empty_embedding),
(6, 'Helps my teen fall asleep', 'Half dose for my teenager works wonders before exams.', '2026-02-21', 4, @empty_embedding),
(6, 'Pairs nicely with magnesium', 'Combination gives me the best rest.', '2026-03-01', 4, @empty_embedding),
(6, 'Relaxes busy mind', 'Calms racing thoughts so I can wind down.', '2026-03-09', 4, @empty_embedding),
(6, 'Tastes neutral', 'Coating keeps it from tasting bitter.', '2026-03-17', 4, @empty_embedding),
(6, 'Dependable on travel days', 'One tablet beats trying to sleep without any help.', '2026-03-25', 4, @empty_embedding),
(6, 'Left me groggy', 'Need at least nine hours or I feel sluggish.', '2026-04-02', 2, @empty_embedding),
(6, 'Bitter when coating chips', 'If it cracks, the taste is awful and sticks around.', '2026-04-10', 2, @empty_embedding),
(6, 'Vivid dreams every night', 'Dreams got too intense so I stopped taking it.', '2026-04-18', 2, @empty_embedding),
(6, 'Packaging cracks easily', 'Cap shattered after one drop which made storage messy.', '2026-04-26', 3, @empty_embedding),
(6, 'Not strong enough for me', 'Still tossed and turned even after two tablets.', '2026-05-04', 2, @empty_embedding),
(6, 'Gave me headaches', 'Woke up with pounding headaches whenever I used it.', '2026-05-12', 2, @empty_embedding),
(6, 'Felt dizzy in the morning', 'Balance felt off for the first hour after waking.', '2026-05-20', 2, @empty_embedding),
(6, 'Hard to split tablets', 'Scored line crumbles when I cut them in half.', '2026-05-28', 2, @empty_embedding),
(6, 'No effect at all', 'Still staring at the ceiling after an hour.', '2026-06-05', 1, @empty_embedding),
(6, 'Body adjusted too quickly', 'Worked for a week and then stopped doing anything.', '2026-06-13', 2, @empty_embedding);